version: "3.3"
services:
  nginx:
    image: nginx:alpine
    container_name: tic-nginx
    working_dir: /application
    volumes:
      - ./${BASE_PATH}:/application
      - ./${DOCKER_PATH}/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - tic-network
    depends_on:
      - php-fpm

  php-fpm:
    build: ${DOCKER_PATH}/php-fpm
    container_name: tic-php-fpm
    working_dir: /application
    volumes:
      - ./${BASE_PATH}:/application
      - ./${DOCKER_PATH}/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      - tic-network
networks:
  tic-network:
